POST http://localhost:3000/api/v1/kirim
Content-Type: application/json

{
  "bpm": 120.5,
  "spo": 75.2,
  "suhu": 39.6
}

####

GET http://localhost/php-api/api/get.php


####


POST http://localhost/php-api/api/post.php
Content-Type: application/json

{
  "bpm": 120.5,
  "spo": 75.2,
  "suhu": 39.6
}


####
GET http://localhost:3000/api/v1/data

####

POST http://localhost:3000/api/v2/kirimesp
Content-Type: application/json

{
  "currentstate": 0,
  "delay": 5000
}

####

GET http://localhost:3000/api/v2/dataesp


####

POST http://localhost:3000/api/createusers
Content-Type: application/json

{
  "name": "Admin",
  "email": "admin2@gmail.com",
  "password": "passwordadmin",
  "role": "admin"
}
